export enum IconType {
    AddRow = 'AddRow',
    AdjustColumns = 'AdjustColumns',
    ArrowDown = 'ArrowDown',
    Back = 'Back',
    Copy = 'Copy',
    Delete = 'Delete',
    DeleteRow = 'DeleteRow',
    Edit = 'Edit',
    Ellipsis = 'Ellipsis',
    ExportToExcel = 'ExportToExcel',
    First = 'First',
    Import = 'Import',
    Insert = 'Insert',
    Last = 'Last',
    Next = 'Next',
    Previous = 'Previous',
    Refresh = 'Refresh',
    Save = 'Save',
    SaveAndBack = 'SaveAndBack',
    Undo = 'Undo',
}
