name: CI Pipeline

on:
  push: # run on push
  workflow_dispatch: # manual run

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build projects
        run: npm run build

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Upload Chrome Extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: acumatica-chrome-extension
          path: chrome-extension/dist
          retention-days: 7

      - name: Upload Figma Plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: acumatica-figma-plugin
          path: figma-plugin/dist
          retention-days: 7
